#!/bin/bash

# Based on the Taskfile format from https://github.com/adriancooney/Taskfile
# Please keep functions sorted alphabetically for ease of future editing.

# Assuming Ubuntu 22.04 LTS
BASEPYTHON=`which python3.10 || which python3 || which python`
BASE_DIR=$(cd `dirname "$0"`; pwd)
PROJECT_NAME=`basename "$BASE_DIR"`
PYTHON="$BASE_DIR/venv/bin/python"

function bootstrap {
    setup_virtualenv
    # Create a default .env file for dev
    [ ! -e "$BASE_DIR/.env" ] && cp $BASE_DIR/example.env $BASE_DIR/.env
    # The settings file should ensure there's a var dir when manage.py runs.
    $PYTHON $BASE_DIR/manage.py migrate
    # This should only be needed once: turn on WAL mode for better concurrency
    SQLITE=`which sqlite3`
    DBFILE="$BASE_DIR/var/db/db.sqlite3"
    [ -n "$SQLITE" ] && [ -e "$DBFILE" ] && $SQLITE $DBFILE 'PRAGMA journal_mode=WAL;'
}

function default {
    server
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function requirements {
    export CUSTOM_COMPILE_COMMAND="./run requirements $@"
    [ -z "$@" ] && echo -e "Adding new requirements.\nNOTE: use --upgrade to bump all versions."
    REQS="$BASE_DIR/etc/requirements"
    ARGS="--no-emit-index-url --generate-hashes --reuse-hashes --resolver=backtracking"
    pip-compile --output-file=requirements.txt $ARGS $@ "$REQS/base.pip.txt" "$REQS/prod.pip.txt"
    pip-compile --output-file=requirements-test.txt $ARGS $@ "$REQS/base.pip.txt" "$REQS/test.pip.txt"
}

function server {
    $PYTHON $BASE_DIR/manage.py runserver
}

function setup_virtualenv() {
    # Create virtualenv and install requirements for dev
    if [ ! -d $BASE_DIR/venv ]; then
        echo "Creating virtualenv in $BASE_DIR/venv"
        $BASEPYTHON -m venv --prompt "$PROJECT_NAME" $BASE_DIR/venv
    fi
    echo "Installing pip requirements. May take a while. Grab a coffee."
    # First, let's upgrade pip so it doesn't complain when installing the rest
    $BASE_DIR/venv/bin/pip install --upgrade -q pip
    $BASE_DIR/venv/bin/pip install -r $BASE_DIR/etc/requirements/dev.pip.txt -q --log $BASE_DIR/venv/pip.log
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
