---
title: "Occam's Moving Parts"
tagline: "Vince Veselosky, Software Architect"
author: "Vince Veselosky"
social:
    Twitter: "https://twitter.com/veselosky"
    Resume on LinkedIn: "https://www.linkedin.com/in/veselosky"
    Code on Github: "https://github.com/veselosky?tab=repositories"
    Facebook: "https://facebook.com/veselosky"
    Google Plus (but I'm rarely there): "https://plus.google.com/+VinceVeselosky"
    Slideshare: "http://www.slideshare.net/veselosky"
