backend:
  name: git-gateway
  branch: fixit2020
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: copyright_licenses
    label: "Copyright License"
    folder: "meta/copyright_licenses"
    extension: json
    format: json
    create: false
    slug: "{{fields.slug}}"
    fields:
      - { label: "License", name: title, widget: string }
      - { label: "License URL", name: license_url, widget: string, required: false }
      - { label: "License Description", name: description, widget: string, required: false }
      - { label: "Slug", name: slug, widget: string, required: true }
      - label: "License Notice"
        name: license_notice
        widget: markdown
        minimal: true
        buttons: [bold, italic, link]

  - name: bylines
    label: "Bylines (Attributions)"
    label_singular: "Byline"
    folder: "meta/bylines"
    extension: json
    format: json
    create: true
    hint: "A byline combines attribution (credit) with copyright details."
    fields:
      - label: "Title"
        name: title
        widget: string
        hint: "An internal name for this attribution, not visible to the public. Typically this will be the pseudonym or copyright holder.",
      - name: description
        label: "Description"
        widget: string
        required: false
        hint: "Internal description (not public)."
      - label: "By Line"
        name: byline
        widget: markdown
        minimal: true
        buttons: [bold, italic, link]
        editor_components: []
        required: false
        hint: "How attribution should appear on site (typically displayed beneath the title, or as a caption with images). May include links to source. May be left blank if attribution is not required/desired. Example: 'Special guest post by Phil Colson, Agent of S.H.I.E.L.D.'",
      - label: "License"
        name: license
        widget: reference
        collection: copyright_licenses
        display_fields: [title, description]
        value_field: slug
        search_fields: [title]
        multiple: false
        default: all-rights-reserved
        hint: "https://creativecommons.org/about/cclicenses/"
      - label: "Copyright Holder"
        name: copyright_holder
        widget: string
        hint: "The legal entity that holds the copyright."
      - label: "Provider"
        name: provider
        widget: string
        required: false
        hint: "Provider is a person or organization that provides access to content through syndication, for example a website like Unsplash.com or a news organization like the Associated Press."
      - label: "Usage Terms"
        name: usage_terms
        widget: text
        required: false
        hint: "Textual description (for humans) describing any restrictions or terms of use."

  - name: authors
    label: Authors
    label_singular: Author
    folder: "meta/authors"
    extension: md
    format: frontmatter
    create: true
    fields:
      - { label: "Template Key", name: templateKey, widget: hidden, default: author }
      - label: "Display Name"
        name: title
        widget: string
      - label: "By Line"
        name: byline
        widget: relation
        collection: bylines
        value_field: slug
        search_fields: [title]
        multiple: false
        default: default
        display_fields: [title, byline]
      - { label: "Author Image (portrait)", name: featuredimage, widget: image, required: false }
      - { label: "About the Author", name: body, widget: markdown, required: false }

  - name: categories
    label: "Categories"
    label_singular: "Category"
    folder: "meta/categories"
    extension: md
    format: frontmatter
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: templateKey, widget: hidden, default: category }
      - { label: "Name", name: title, widget: string }
      - { label: "Description", name: description, widget: text, required: false }
      - { label: "Default Image", name: defaultimage, widget: image, required: false }
      - { label: "Body", name: body, widget: markdown, required: false }

  - name: blog
    label: "Blog"
    label_singular: "Blog Post"
    folder: "blog"
    extension: md
    format: frontmatter
    create: true
    slug: "{{category}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "article" }
      - { label: "Short Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Updated Date", name: "updated", widget: "datetime" }
      - { label: "SEO Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page" }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        { label: Description, name: description, widget: string },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
